"""Clips multi-platform packaging, platform presets, and YouTube Shorts publishing."""

from __future__ import annotations

import os
import shutil
from typing import Dict, List, Optional

import paths
from clips.models import CandidateClip, ClipProject
from clips.reframing import render_vertical_clip
from providers.publish.youtube_provider import YouTubeProvider


PLATFORM_PRESETS = {
    "youtube_shorts": {
        "aspect_ratio": "9:16",
        "width": 1080,
        "height": 1920,
        "max_duration": 60.0,
        "fps": 30,
        "title_suffix": " #Shorts",
    },
    "instagram_reels": {
        "aspect_ratio": "9:16",
        "width": 1080,
        "height": 1920,
        "max_duration": 90.0,
        "fps": 30,
        "safe_margin_bottom": 0.18,
    },
    "tiktok": {
        "aspect_ratio": "9:16",
        "width": 1080,
        "height": 1920,
        "max_duration": 180.0,
        "fps": 30,
    },
    "landscape": {
        "aspect_ratio": "16:9",
        "width": 1920,
        "height": 1080,
        "max_duration": 300.0,
        "fps": 30,
    },
}


def publish_short_to_youtube(
    clip: CandidateClip,
    rendered_clip_path: str,
    title: str,
    description: str = "",
    tags: Optional[List[str]] = None,
    privacy_status: str = "private",
    dry_run: bool = False,
) -> dict:
    """Uploads a vertical clip directly to YouTube as a YouTube Short."""
    preset = PLATFORM_PRESETS["youtube_shorts"]
    if clip.duration > preset["max_duration"]:
        raise ValueError(
            f"Clip duration ({clip.duration:.1f}s) exceeds YouTube Shorts cap ({preset['max_duration']}s)"
        )

    # Ensure title contains #Shorts
    clean_title = title.strip()
    if "#Shorts" not in clean_title and "#shorts" not in clean_title:
        clean_title = (clean_title[:85] + preset["title_suffix"]).strip()

    short_tags = list(tags or [])
    if "Shorts" not in short_tags and "shorts" not in short_tags:
        short_tags.append("Shorts")

    provider = YouTubeProvider(dry_run=dry_run)
    return provider.upload(
        video_path=rendered_clip_path,
        title=clean_title,
        description=description or f"{clean_title}\n\nGenerated by Santa Studio Clips.",
        tags=short_tags,
        privacy_status=privacy_status,
    )


def format_for_platform(clip: CandidateClip, platform: str) -> dict:
    """How this clip has to be cut and sized for one target.

    Returns the concrete numbers a render needs: frame size, fps, the end
    time after the platform's duration cap is applied, and the fraction of
    the frame that platform's own UI covers, which captions must stay clear
    of.
    """
    if platform not in PLATFORM_PRESETS:
        raise ValueError(
            f"Unknown platform {platform!r}. Available: {sorted(PLATFORM_PRESETS)}"
        )
    preset = PLATFORM_PRESETS[platform]

    cap = float(preset["max_duration"])
    duration = min(clip.duration, cap)
    return {
        "platform": platform,
        "width": preset["width"],
        "height": preset["height"],
        "fps": preset["fps"],
        "aspect_ratio": preset["aspect_ratio"],
        "start_time": clip.start_time,
        "end_time": round(clip.start_time + duration, 2),
        "duration": round(duration, 2),
        "truncated": clip.duration > cap,
        "safe_margin_bottom": preset.get("safe_margin_bottom", 0.0),
    }


def package_clips_bundle(
    project: ClipProject,
    output_directory: str | None = None,
    platforms: Optional[List[str]] = None,
) -> dict:
    """Renders every candidate for every requested platform.

    `platforms` was accepted and then never used: one 9:16 master was
    rendered whatever was asked for, so a TikTok cut and an Instagram cut
    were the same file at the same length, and `landscape` produced a
    vertical crop. Each target now gets its own render at its own size,
    truncated to its own duration cap.
    """
    platforms = platforms or ["youtube_shorts", "instagram_reels", "tiktok"]
    unknown = [p for p in platforms if p not in PLATFORM_PRESETS]
    if unknown:
        raise ValueError(
            f"Unknown platform(s) {unknown}. Available: {sorted(PLATFORM_PRESETS)}"
        )

    if output_directory is None:
        output_directory = str(
            paths.output_dir(project.project_id, project.source.title or "clips") / "bundle"
        )
    os.makedirs(output_directory, exist_ok=True)

    have_source = bool(project.source.video_path) and os.path.exists(project.source.video_path)

    package_manifest = {
        "project_id": project.project_id,
        "source_title": project.source.title,
        "platforms": list(platforms),
        "clips": [],
    }

    for clip in project.candidates:
        clip_entry = {
            "clip_id": clip.clip_id,
            "title": clip.suggested_title or clip.hook_text,
            "duration": clip.duration,
            "formats": {},
            "files": {},
        }

        for platform in platforms:
            spec = format_for_platform(clip, platform)
            clip_entry["formats"][platform] = spec

            if not have_source:
                continue

            filename = f"{clip.clip_id}_{platform}.mp4"
            target_path = os.path.join(output_directory, filename)
            try:
                render_vertical_clip(
                    source_video_path=project.source.video_path,
                    start_time=spec["start_time"],
                    end_time=spec["end_time"],
                    output_path=target_path,
                    crop_x_center_ratio=clip.crop_x_offset,
                    width=spec["width"],
                    height=spec["height"],
                    fps=spec["fps"],
                )
                clip_entry["files"][platform] = target_path
            except Exception as e:
                clip_entry.setdefault("errors", {})[platform] = str(e)

        package_manifest["clips"].append(clip_entry)

    return package_manifest
