"""Clips multi-platform packaging, platform presets, and YouTube Shorts publishing."""

from __future__ import annotations

import os
import shutil
from typing import Dict, List, Optional

from clips.models import CandidateClip, ClipProject
from clips.reframing import render_vertical_clip
from providers.publish.youtube_provider import YouTubeProvider


PLATFORM_PRESETS = {
    "youtube_shorts": {
        "aspect_ratio": "9:16",
        "width": 1080,
        "height": 1920,
        "max_duration": 60.0,
        "fps": 30,
        "title_suffix": " #Shorts",
    },
    "instagram_reels": {
        "aspect_ratio": "9:16",
        "width": 1080,
        "height": 1920,
        "max_duration": 90.0,
        "fps": 30,
        "safe_margin_bottom": 0.18,
    },
    "tiktok": {
        "aspect_ratio": "9:16",
        "width": 1080,
        "height": 1920,
        "max_duration": 180.0,
        "fps": 30,
    },
    "landscape": {
        "aspect_ratio": "16:9",
        "width": 1920,
        "height": 1080,
        "max_duration": 300.0,
        "fps": 30,
    },
}


def publish_short_to_youtube(
    clip: CandidateClip,
    rendered_clip_path: str,
    title: str,
    description: str = "",
    tags: Optional[List[str]] = None,
    privacy_status: str = "private",
    dry_run: bool = False,
) -> dict:
    """Uploads a vertical clip directly to YouTube as a YouTube Short."""
    preset = PLATFORM_PRESETS["youtube_shorts"]
    if clip.duration > preset["max_duration"] + 1.0:
        raise ValueError(
            f"Clip duration ({clip.duration:.1f}s) exceeds YouTube Shorts cap ({preset['max_duration']}s)"
        )

    # Ensure title contains #Shorts
    clean_title = title.strip()
    if "#Shorts" not in clean_title and "#shorts" not in clean_title:
        clean_title = (clean_title[:85] + preset["title_suffix"]).strip()

    short_tags = list(tags or [])
    if "Shorts" not in short_tags and "shorts" not in short_tags:
        short_tags.append("Shorts")

    provider = YouTubeProvider(dry_run=dry_run)
    return provider.upload(
        video_path=rendered_clip_path,
        title=clean_title,
        description=description or f"{clean_title}\n\nGenerated by Santa Studio Clips.",
        tags=short_tags,
        privacy_status=privacy_status,
    )


def package_clips_bundle(
    project: ClipProject,
    output_directory: str = "runs/clips/bundle",
    platforms: Optional[List[str]] = None,
) -> dict:
    """Renders and packages all candidate clips formatted for specified platforms."""
    platforms = platforms or ["youtube_shorts", "instagram_reels", "tiktok"]
    os.makedirs(output_directory, exist_ok=True)

    package_manifest = {
        "project_id": project.project_id,
        "source_title": project.source.title,
        "clips": [],
    }

    for clip in project.candidates:
        clip_entry = {
            "clip_id": clip.clip_id,
            "title": clip.suggested_title or clip.hook_text,
            "duration": clip.duration,
            "files": {},
        }

        # Render 9:16 master if source video exists
        if project.source.video_path and os.path.exists(project.source.video_path):
            clip_filename = f"{project.project_id}_{clip.clip_id}_9x16.mp4"
            target_path = os.path.join(output_directory, clip_filename)

            try:
                render_vertical_clip(
                    source_video_path=project.source.video_path,
                    start_time=clip.start_time,
                    end_time=clip.end_time,
                    output_path=target_path,
                    crop_x_center_ratio=clip.crop_x_offset,
                )
                clip_entry["files"]["master_9x16"] = target_path
            except Exception as e:
                clip_entry["files"]["error"] = str(e)

        package_manifest["clips"].append(clip_entry)

    return package_manifest
